Vagrant.configure("2") do |config|
    
   (1..2).each do |i|
    
    config.vm.define "node#{i}" do |subconfig|
      subconfig.vm.box = "ubuntu/trusty64"
      subconfig.vm.hostname = "node#{i}"
      subconfig.vm.network :private_network, ip: "192.168.56.#{i + 10}"
      config.ssh.insert_key = false
      config.vm.boot_timeout = 800
      config.ssh.private_key_path =['~\\.ssh\\id_rsa' ,'~\\.vagrant.d\\insecure_private_key']
      config.vm.provision "file", source:"~\\.ssh\\id_rsa.pub", destination: "~/.ssh/authorized_keys"
      config.vm.provision "shell", inline: "sudo apt-get install git -y"
 end 
  end

end
